# 线上配置文件
# @author <a href="https://github.com/JavaBo14">Bo</a>
# @from <a href="https://github.com/JavaBo14/Bi">
server:
  port: 8080
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.83.24.78:3306/bopao
    username: BoPao
    password: 123123
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 47.83.24.78
    port: 6379
    timeout: 5000
    password: 1014
  #    password: 123456
  # Elasticsearch 配置
  # todo 需替换配置
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: bo
    password: 1014
